"""
Stage 2 Phase 2: BART meme conditioning fine-tune.

Fine-tunes BART (starting from the Phase 1 ParaDetox checkpoint) on the
pseudo-labelled meme pairs generated by Stage 1 LLaVA.
Run once per conditioning condition (full / target_only / attack_only / none).

Pipeline position: AFTER train_stage2_phase1, using dataset from build_stage2_dataset.

Usage (cluster):
    python training/train_stage2_phase2.py \
        --condition full \
        --phase1_checkpoint_dir /scratch/hmr_stage2_phase1_checkpoint \
        --dataset_dir           /scratch/hmr_stage2_dataset \
        --output_dir            /scratch/hmr_stage2_phase2_full_checkpoint \
        --hf_cache              /scratch/hf_cache \
        --num_train_epochs 3 \
        --per_device_train_batch_size 8 \
        --learning_rate 2e-5 \
        --warmup_steps 100 \
        --weight_decay 0.01 \
        --seed 42
"""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, List, Literal

import torch
from torch.utils.data import Dataset

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.debug import DEBUG_CONFIG, is_debug_mode, set_seeds, make_debug_dataset

logger = logging.getLogger(__name__)

CONDITION_TYPE = Literal["full", "target_only", "attack_only", "none"]


# ---------------------------------------------------------------------------
# Input formatting  (mirrors MemeRewriter.format_input)
# ---------------------------------------------------------------------------

def format_input(
    original_text: str,
    target_group: str,
    attack_type: str,
    implicit_meaning: str,
    condition: str,
) -> str:
    """Build BART encoder input string for the given condition."""
    tg = target_group   or "null"
    at = attack_type    or "null"
    im = implicit_meaning or "null"

    if condition == "full":
        prefix = f"[T: {tg}] [A: {at}] [M: {im}]"
    elif condition == "target_only":
        prefix = f"[T: {tg}] [A: null] [M: null]"
    elif condition == "attack_only":
        prefix = f"[T: null] [A: {at}] [M: null]"
    else:  # "none"
        prefix = "[T: null] [A: null] [M: null]"

    return f"{prefix} </s> {original_text}"


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class MemeRewriteDataset(Dataset):
    """Meme pseudo-rewrite pairs with condition-specific BART encoder inputs."""

    def __init__(self, examples: List[Dict], tokenizer, condition: str,
                 max_input_length: int = 128, max_target_length: int = 128):
        self.examples = examples
        self.tokenizer = tokenizer
        self.condition = condition
        self.max_input_length = max_input_length
        self.max_target_length = max_target_length

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        ex = self.examples[idx]

        input_text = format_input(
            original_text=ex.get("original_text", ""),
            target_group=ex.get("target_group"),
            attack_type=ex.get("attack_type"),
            implicit_meaning=ex.get("implicit_meaning"),
            condition=self.condition,
        )
        target_text = ex.get("target_text", "")

        model_inputs = self.tokenizer(
            input_text,
            max_length=self.max_input_length,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )
        with self.tokenizer.as_target_tokenizer():
            labels = self.tokenizer(
                target_text,
                max_length=self.max_target_length,
                truncation=True,
                padding="max_length",
                return_tensors="pt",
            )

        label_ids = labels["input_ids"].squeeze()
        label_ids[label_ids == self.tokenizer.pad_token_id] = -100

        return {
            "input_ids":      model_inputs["input_ids"].squeeze(),
            "attention_mask": model_inputs["attention_mask"].squeeze(),
            "labels":         label_ids,
        }


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_jsonl(path: Path) -> List[Dict]:
    examples = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))
    return examples


def load_dataset(dataset_dir: str, debug: bool) -> tuple:
    """Load train.jsonl and val.jsonl from the Stage 2 dataset directory."""
    if debug:
        raw = make_debug_dataset(n=DEBUG_CONFIG["max_samples"])
        # Convert debug format to training format
        examples = [
            {
                "original_text":   e["text"],
                "target_text":     e.get("explanation", {}).get("implicit_meaning", e["text"]),
                "target_group":    e.get("target_group"),
                "attack_type":     e.get("attack_type"),
                "implicit_meaning": (e.get("explanation") or {}).get("implicit_meaning"),
                "dataset":         "debug",
            }
            for e in raw
        ]
        split = max(1, len(examples) - 2)
        return examples[:split], examples[split:]

    d = Path(dataset_dir)
    train_path = d / "train.jsonl"
    val_path   = d / "val.jsonl"

    if not train_path.exists():
        logger.error(f"train.jsonl not found at {train_path}. Run build_stage2_dataset.py first.")
        sys.exit(1)

    train_examples = load_jsonl(train_path)
    val_examples   = load_jsonl(val_path) if val_path.exists() else train_examples[:max(1, len(train_examples) // 10)]

    logger.info(f"Loaded {len(train_examples)} train, {len(val_examples)} val examples")
    return train_examples, val_examples


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Stage 2 Phase 2: BART meme conditioning fine-tune")
    parser.add_argument("--condition",
                        type=str, required=True,
                        choices=["full", "target_only", "attack_only", "none"],
                        help="Conditioning strategy for the ablation study")
    parser.add_argument("--phase1_checkpoint_dir", type=str, required=True,
                        help="Directory of the Phase 1 checkpoint (output of train_stage2_phase1.py)")
    parser.add_argument("--dataset_dir",           type=str, required=True,
                        help="Directory with train.jsonl/val.jsonl (output of build_stage2_dataset.py)")
    parser.add_argument("--output_dir",            type=str, required=True)
    parser.add_argument("--hf_cache",              type=str, default=None)
    parser.add_argument("--num_train_epochs",            type=int,   default=3)
    parser.add_argument("--per_device_train_batch_size", type=int,   default=8)
    parser.add_argument("--learning_rate",               type=float, default=2e-5)
    parser.add_argument("--warmup_steps",                type=int,   default=100)
    parser.add_argument("--weight_decay",                type=float, default=0.01)
    parser.add_argument("--seed",                        type=int,   default=42)
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    debug = is_debug_mode(args)
    set_seeds(args.seed)

    logging.basicConfig(
        level=logging.DEBUG if debug else logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    if args.hf_cache:
        os.environ["HF_HOME"] = args.hf_cache

    # -----------------------------------------------------------------------
    # Model / hyperparameters
    # -----------------------------------------------------------------------
    # Phase 2 always starts from the Phase 1 checkpoint
    checkpoint = args.phase1_checkpoint_dir
    num_epochs  = DEBUG_CONFIG["num_train_epochs"] if debug else args.num_train_epochs
    train_batch = DEBUG_CONFIG["per_device_train_batch_size"] if debug else args.per_device_train_batch_size
    max_steps   = DEBUG_CONFIG["max_steps"] if debug else -1
    save_steps  = DEBUG_CONFIG["save_steps"] if debug else 200
    eval_steps  = DEBUG_CONFIG["eval_steps"] if debug else 200
    fp16        = (not debug) and torch.cuda.is_available()

    logger.info(f"Condition: {args.condition} | checkpoint: {checkpoint} | fp16: {fp16}")

    try:
        from transformers import (
            BartForConditionalGeneration,
            BartTokenizer,
            Seq2SeqTrainer,
            Seq2SeqTrainingArguments,
            DataCollatorForSeq2Seq,
        )
        import evaluate as hf_evaluate
    except ImportError as e:
        logger.error(f"Missing package: {e}. Install: pip install transformers evaluate")
        sys.exit(1)

    tokenizer = BartTokenizer.from_pretrained(checkpoint, cache_dir=args.hf_cache)
    model     = BartForConditionalGeneration.from_pretrained(checkpoint, cache_dir=args.hf_cache)

    # -----------------------------------------------------------------------
    # Data
    # -----------------------------------------------------------------------
    train_examples, val_examples = load_dataset(args.dataset_dir, debug)

    train_dataset = MemeRewriteDataset(train_examples, tokenizer, args.condition)
    val_dataset   = MemeRewriteDataset(val_examples,   tokenizer, args.condition)

    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, label_pad_token_id=-100)

    # -----------------------------------------------------------------------
    # Metrics
    # -----------------------------------------------------------------------
    rouge = hf_evaluate.load("rouge")

    def compute_metrics(eval_pred):
        preds, labels = eval_pred
        if isinstance(preds, tuple):
            preds = preds[0]
        decoded_preds  = tokenizer.batch_decode(preds,  skip_special_tokens=True)
        labels[labels == -100] = tokenizer.pad_token_id
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
        return {k: round(v, 4) for k, v in result.items()}

    # -----------------------------------------------------------------------
    # Training
    # -----------------------------------------------------------------------
    training_args = Seq2SeqTrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=num_epochs,
        max_steps=max_steps,
        per_device_train_batch_size=train_batch,
        per_device_eval_batch_size=train_batch,
        learning_rate=args.learning_rate,
        warmup_steps=args.warmup_steps,
        weight_decay=args.weight_decay,
        fp16=fp16,
        predict_with_generate=True,
        generation_max_length=128,
        evaluation_strategy="steps",
        eval_steps=eval_steps,
        save_strategy="steps",
        save_steps=save_steps,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        logging_steps=DEBUG_CONFIG["logging_steps"] if debug else 50,
        seed=args.seed,
        report_to="none",
        save_total_limit=2,
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    logger.info(f"Starting Phase 2 training (condition={args.condition})...")
    trainer.train()
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    logger.info(f"Phase 2 ({args.condition}) checkpoint saved to {args.output_dir}")


if __name__ == "__main__":
    main()
